### ISSUE TITLE
Как пользователь я хочу иметь возможность добавлять шаблон обращения 

### ISSUE THREAD

**Issue by mih-kopylov** [mih-kopylov/myspb#3]
поля 
  - название 
  - текст обращения 
  - категория из доступных на сайте 
  - тип местоположения: координаты GPS (другой тип местоположения появится позже)

**Comment by triz-ri** [comment]
Вероятно, имеет смысл, чтобы у Пользователя была возможность, выбрать чужой шаблон (например, используем опцию «У меня такая же проблема...», тогда, поскольку он уже авторизовался, приложение копирует ему этот шаблон, автоматически заменяя содержимое полей с личными данными; ему останется только прокомментировать и сделать своё фото).

Тогда, Михаил, у Вас будет возможность не только делиться своими шаблонами со всеми, но и делать для всех какие-либо «якорные» шаблоны для «раскрутки».

**Comment by mih-kopylov** [comment]
@triz-ri 
Шаблон - это всего лишь категория + текст пользователя. 
Это не какая-то особо ценная информация, которой можно делиться и которую имеет смысл искать.

**Comment by triz-ri** [comment]
Дело не в «ценности», а в том, что мне не надо создавать своего шаблона, когда я указываю «Здесь то же самое». Шаблон для меня создаётся автоматически, и мой месседж уходит автоматически в нужные ведомства.
