### ISSUE TITLE
Как пользователь я хочу, чтобы приложение указывало при обращении ближайший дом вместо GPS координат для тех категорий, которые это требуют

### ISSUE THREAD

**Issue by mih-kopylov** [mih-kopylov/myspb#8]
Для некоторых категорий обращения портал требует указать не координаты, а адрес дома, к которому относится обращение.
Чтоб пользователь не вводил адрес, приложение должно находить ближайший к нему дом, используя GPS координаты

**Comment by triz-ri** [comment]
Можно использовать api сервиса dadata.ru - тогда можно автоматически получить в приложение данные, в том числе, по ближайшему объекту - Пользователю не потребуется (в том числе, в незнакомых местах) искать таблички, думать как заполнить и т.д.

**Comment by mih-kopylov** [comment]
@triz-ri 
Для этой задачи уже есть публичный REST API на портале: https://gorod.gov.spb.ru/public_api/maps/get_building_by_coordinates/?lat=59.92205449669454&lon=30.33318690955639
